root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "logs", ".git"]
  delay = 300
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
